// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDR9Pj8AuQTmiHwBpLqDAl96oL0898p6hs',
    appId: '1:72388048866:web:fc5f89a34630f500fcebbb',
    messagingSenderId: '72388048866',
    projectId: 'shopbiz-5ed6e',
    authDomain: 'shopbiz-5ed6e.firebaseapp.com',
    storageBucket: 'shopbiz-5ed6e.firebasestorage.app',
    measurementId: 'G-798KES17KH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAm7Izk04Gvw9fcz_Put-1Pg9r3WwwllL8',
    appId: '1:72388048866:android:d2964b11d2e0c81bfcebbb',
    messagingSenderId: '72388048866',
    projectId: 'shopbiz-5ed6e',
    storageBucket: 'shopbiz-5ed6e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnoNbZaAKtgHRx1Uwzkw-4Hj3EFrPf-aY',
    appId: '1:72388048866:ios:01e47a267447e89efcebbb',
    messagingSenderId: '72388048866',
    projectId: 'shopbiz-5ed6e',
    storageBucket: 'shopbiz-5ed6e.firebasestorage.app',
    iosBundleId: 'com.example.shopbiz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnoNbZaAKtgHRx1Uwzkw-4Hj3EFrPf-aY',
    appId: '1:72388048866:ios:01e47a267447e89efcebbb',
    messagingSenderId: '72388048866',
    projectId: 'shopbiz-5ed6e',
    storageBucket: 'shopbiz-5ed6e.firebasestorage.app',
    iosBundleId: 'com.example.shopbiz',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDR9Pj8AuQTmiHwBpLqDAl96oL0898p6hs',
    appId: '1:72388048866:web:2fe09555dca20aaafcebbb',
    messagingSenderId: '72388048866',
    projectId: 'shopbiz-5ed6e',
    authDomain: 'shopbiz-5ed6e.firebaseapp.com',
    storageBucket: 'shopbiz-5ed6e.firebasestorage.app',
    measurementId: 'G-TZDFJ28HH4',
  );
}
